"""
Caption template definitions for animated subtitles.
Each template defines styling and animation properties for different caption styles.
"""

from typing import Dict, Any, Literal

AnimationType = Literal[
    "none", "karaoke", "pop", "fade", "bounce",
    "slide_up", "slide_down", "slide_left", "slide_right",
    "typewriter", "scale_in", "reveal",
]

PositionType = Literal["bottom", "middle", "top"]

CAPTION_TEMPLATES: Dict[str, Dict[str, Any]] = {
    "default": {
        "name": "Default",
        "description": "Clean white text with black outline",
        "font_family": "THEBOLDFONT",
        "font_size": 64,
        "font_color": "#FFFFFF",
        "highlight_color": "#FFD700",
        "stroke_color": "#000000",
        "stroke_width": 2,
        "background": False,
        "background_color": None,
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "none",
        "animation_speed": 1.0,
        "shadow": False,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.75,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
    "hormozi": {
        "name": "Hormozi",
        "description": "Bold green highlights like Alex Hormozi's videos",
        "font_family": "THEBOLDFONT",
        "font_size": 48,
        "font_color": "#FFFFFF",
        "highlight_color": "#00FF00",
        "stroke_color": "#000000",
        "stroke_width": 3,
        "background": True,
        "background_color": "#000000AA",
        "background_padding": 10,
        "background_border_radius": 4,
        "animation": "karaoke",
        "animation_speed": 1.0,
        "shadow": True,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.75,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
    "mrbeast": {
        "name": "MrBeast",
        "description": "Large yellow text with red highlights",
        "font_family": "THEBOLDFONT",
        "font_size": 56,
        "font_color": "#FFFF00",
        "highlight_color": "#FF0000",
        "stroke_color": "#000000",
        "stroke_width": 4,
        "background": False,
        "background_color": None,
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "pop",
        "animation_speed": 1.0,
        "shadow": True,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.70,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
    "minimal": {
        "name": "Minimal",
        "description": "Clean, subtle captions with transparent background",
        "font_family": "TikTokSans-Regular",
        "font_size": 40,
        "font_color": "#FFFFFF",
        "highlight_color": "#CCCCCC",
        "stroke_color": None,
        "stroke_width": 0,
        "background": True,
        "background_color": "#00000080",
        "background_padding": 6,
        "background_border_radius": 4,
        "animation": "fade",
        "animation_speed": 1.0,
        "shadow": False,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.80,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
    "tiktok": {
        "name": "TikTok",
        "description": "TikTok-style with pink highlights",
        "font_family": "TikTokSans-Regular",
        "font_size": 48,
        "font_color": "#FFFFFF",
        "highlight_color": "#FE2C55",
        "stroke_color": "#000000",
        "stroke_width": 2,
        "background": False,
        "background_color": None,
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "karaoke",
        "animation_speed": 1.0,
        "shadow": True,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.75,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
    "neon": {
        "name": "Neon",
        "description": "Glowing neon effect with cyan highlights",
        "font_family": "THEBOLDFONT",
        "font_size": 48,
        "font_color": "#00FFFF",
        "highlight_color": "#FF00FF",
        "stroke_color": "#000066",
        "stroke_width": 2,
        "background": False,
        "background_color": None,
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "karaoke",
        "animation_speed": 1.0,
        "shadow": True,
        "shadow_offset_x": 3,
        "shadow_offset_y": 3,
        "shadow_color": "#FF00FF",
        "shadow_blur": 2.0,
        "position": "bottom",
        "position_y": 0.75,
        "letter_spacing": 1,
        "line_height": 1.0,
        "uppercase": True,
    },
    "podcast": {
        "name": "Podcast",
        "description": "Professional podcast-style captions",
        "font_family": "TikTokSans-Regular",
        "font_size": 42,
        "font_color": "#FFFFFF",
        "highlight_color": "#FFB800",
        "stroke_color": "#333333",
        "stroke_width": 1,
        "background": True,
        "background_color": "#1A1A1ACC",
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "fade",
        "animation_speed": 1.0,
        "shadow": False,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.78,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
    "cinematic": {
        "name": "Cinematic",
        "description": "Professional cinema-style captions with slide-up animation",
        "font_family": "THEBOLDFONT",
        "font_size": 52,
        "font_color": "#FFFFFF",
        "highlight_color": "#FFD700",
        "stroke_color": "#000000",
        "stroke_width": 3,
        "background": True,
        "background_color": "#00000088",
        "background_padding": 12,
        "background_border_radius": 6,
        "animation": "slide_up",
        "animation_speed": 0.8,
        "shadow": True,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.5,
        "position": "bottom",
        "position_y": 0.78,
        "letter_spacing": 1,
        "line_height": 1.1,
        "uppercase": False,
    },
    "premium": {
        "name": "Premium",
        "description": "Premium typewriter-style captions with reveal effect",
        "font_family": "THEBOLDFONT",
        "font_size": 50,
        "font_color": "#FFFFFF",
        "highlight_color": "#FFD700",
        "stroke_color": "#222222",
        "stroke_width": 2,
        "background": True,
        "background_color": "#00000099",
        "background_padding": 10,
        "background_border_radius": 6,
        "animation": "typewriter",
        "animation_speed": 0.6,
        "shadow": True,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.76,
        "letter_spacing": 1,
        "line_height": 1.0,
        "uppercase": False,
    },
    "reveal": {
        "name": "Reveal",
        "description": "Text reveals left-to-right with clean style",
        "font_family": "TikTokSans-Regular",
        "font_size": 44,
        "font_color": "#FFFFFF",
        "highlight_color": "#4FC3F7",
        "stroke_color": "#000000",
        "stroke_width": 2,
        "background": True,
        "background_color": "#00000077",
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "reveal",
        "animation_speed": 0.9,
        "shadow": True,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "middle",
        "position_y": 0.55,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
    "bounce": {
        "name": "Bounce",
        "description": "Energetic bouncy text perfect for fast-paced content",
        "font_family": "THEBOLDFONT",
        "font_size": 60,
        "font_color": "#FFFFFF",
        "highlight_color": "#FF6B6B",
        "stroke_color": "#000000",
        "stroke_width": 3,
        "background": False,
        "background_color": None,
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "bounce",
        "animation_speed": 1.0,
        "shadow": True,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.70,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
}

POSITION_Y_MAP: Dict[str, float] = {
    "top": 0.18,
    "middle": 0.52,
    "bottom": 0.75,
}


def get_template(template_name: str) -> Dict[str, Any]:
    """Get a caption template by name, returns default if not found."""
    return CAPTION_TEMPLATES.get(template_name, CAPTION_TEMPLATES["default"])


def get_all_templates() -> Dict[str, Dict[str, Any]]:
    """Get all available caption templates."""
    return CAPTION_TEMPLATES


def get_template_names() -> list:
    """Get list of all template names."""
    return list(CAPTION_TEMPLATES.keys())


def get_template_info() -> list:
    """Get list of template info for API response."""
    return [
        {
            "id": name,
            "name": template["name"],
            "description": template["description"],
            "animation": template["animation"],
            "animation_speed": template.get("animation_speed", 1.0),
            "font_family": template["font_family"],
            "font_size": template["font_size"],
            "font_color": template["font_color"],
            "highlight_color": template["highlight_color"],
            "stroke_color": template.get("stroke_color"),
            "stroke_width": template.get("stroke_width", 0),
            "position": template.get("position", "bottom"),
            "background": template.get("background", False),
            "shadow": template.get("shadow", False),
            "letter_spacing": template.get("letter_spacing", 0),
            "uppercase": template.get("uppercase", False),
        }
        for name, template in CAPTION_TEMPLATES.items()
    ]
