"""
Caption template definitions for animated subtitles.
Each template defines styling and animation properties for different caption styles.
"""

from typing import Dict, Any, Literal

AnimationType = Literal[
    "none", "karaoke", "pop", "fade", "bounce",
    "slide_up", "slide_down", "slide_left", "slide_right",
    "typewriter", "scale_in", "reveal",
]

PositionType = Literal["bottom", "middle", "top"]

CAPTION_TEMPLATES: Dict[str, Dict[str, Any]] = {
    "default": {
        "name": "Default",
        "description": "Clean white text with black outline",
        "font_family": "THEBOLDFONT",
        "font_size": 64,
        "font_color": "#FFFFFF",
        "highlight_color": "#FFD700",
        "stroke_color": "#000000",
        "stroke_width": 2,
        "background": False,
        "background_color": None,
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "none",
        "animation_speed": 1.0,
        "shadow": False,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.85,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
    "minimal": {
        "name": "Minimal",
        "description": "Small, clean text at the bottom",
        "font_family": "TikTokSans-Regular",
        "font_size": 48,
        "font_color": "#FFFFFF",
        "highlight_color": "#FFD700",
        "stroke_color": "#000000",
        "stroke_width": 1,
        "background": False,
        "background_color": None,
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "fade",
        "animation_speed": 1.0,
        "shadow": False,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.90,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
    "karaoke": {
        "name": "Karaoke",
        "description": "Word-by-word highlight karaoke style",
        "font_family": "TikTokSans-Regular",
        "font_size": 56,
        "font_color": "#FFFFFF",
        "highlight_color": "#FFD700",
        "stroke_color": "#000000",
        "stroke_width": 2,
        "background": False,
        "background_color": None,
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "karaoke",
        "animation_speed": 1.0,
        "shadow": False,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.85,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
    "pop": {
        "name": "Pop",
        "description": "Bold pop-style captions with scale effect",
        "font_family": "THEBOLDFONT",
        "font_size": 60,
        "font_color": "#FFFFFF",
        "highlight_color": "#FF6B6B",
        "stroke_color": "#000000",
        "stroke_width": 2,
        "background": False,
        "background_color": None,
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "pop",
        "animation_speed": 1.2,
        "shadow": False,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.85,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
    "fade": {
        "name": "Fade",
        "description": "Smooth fade in/out captions",
        "font_family": "TikTokSans-Regular",
        "font_size": 52,
        "font_color": "#FFFFFF",
        "highlight_color": "#FFD700",
        "stroke_color": "#000000",
        "stroke_width": 2,
        "background": False,
        "background_color": None,
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "fade",
        "animation_speed": 1.0,
        "shadow": False,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.85,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
    "typewriter": {
        "name": "Typewriter",
        "description": "Words appear one by one like a typewriter",
        "font_family": "TikTokSans-Regular",
        "font_size": 52,
        "font_color": "#FFFFFF",
        "highlight_color": "#FFD700",
        "stroke_color": "#000000",
        "stroke_width": 2,
        "background": False,
        "background_color": None,
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "typewriter",
        "animation_speed": 1.0,
        "shadow": False,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.85,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
    "scale_in": {
        "name": "Scale In",
        "description": "Words scale in from small to full size",
        "font_family": "THEBOLDFONT",
        "font_size": 58,
        "font_color": "#FFFFFF",
        "highlight_color": "#FFD700",
        "stroke_color": "#000000",
        "stroke_width": 2,
        "background": False,
        "background_color": None,
        "background_padding": 8,
        "background_border_radius": 4,
        "animation": "scale_in",
        "animation_speed": 1.0,
        "shadow": False,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "shadow_color": "#000000",
        "shadow_blur": 1.0,
        "position": "bottom",
        "position_y": 0.85,
        "letter_spacing": 0,
        "line_height": 1.0,
        "uppercase": False,
    },
}

POSITION_Y_MAP: Dict[str, float] = {
    "top": 0.18,
    "middle": 0.52,
    "bottom": 0.75,
}


def get_template(template_name: str) -> Dict[str, Any]:
    """Get a caption template by name, returns default if not found."""
    return CAPTION_TEMPLATES.get(template_name, CAPTION_TEMPLATES["default"])


def get_all_templates() -> Dict[str, Dict[str, Any]]:
    """Get all available caption templates."""
    return CAPTION_TEMPLATES


def get_template_names() -> list:
    """Get list of all template names."""
    return list(CAPTION_TEMPLATES.keys())


def get_template_info() -> list:
    """Get list of template info for API response."""
    return [
        {
            "id": name,
            "name": template["name"],
            "description": template["description"],
            "animation": template["animation"],
            "animation_speed": template.get("animation_speed", 1.0),
            "font_family": template["font_family"],
            "font_size": template["font_size"],
            "font_color": template["font_color"],
            "highlight_color": template["highlight_color"],
            "stroke_color": template.get("stroke_color"),
            "stroke_width": template.get("stroke_width", 0),
            "position": template.get("position", "bottom"),
            "background": template.get("background", False),
            "shadow": template.get("shadow", False),
            "letter_spacing": template.get("letter_spacing", 0),
            "uppercase": template.get("uppercase", False),
        }
        for name, template in CAPTION_TEMPLATES.items()
    ]
